.release:
  stage: release
  image: ${CI_IMAGE}

.release_S3:
  dependencies:
  - darwin amd64
  - linux amd64
  - linux arm
  - linux arm64
  - openbsd amd64
  - windows amd64
  variables:
    S3_URL: s3://${S3_BUCKET}/${CI_COMMIT_REF_NAME}
  script:
  - ./.gitlab/ci/scripts/release_s3.sh
  environment:
    url: https://${S3_BUCKET}.s3.amazonaws.com/${CI_COMMIT_REF_NAME}/index.html

release development S3:
  extends:
  - .rules:release:development
  - .release
  - .release_S3
  environment:
    name: development/S3/${CI_COMMIT_REF_NAME}
    on_stop: stop release development S3

stop release development S3:
  dependencies: []
  extends:
  - .rules:release:development
  - .release
  - .release_S3
  variables:
    GIT_STRATEGY: none
  script:
  - aws s3 rm ${S3_URL} --recursive
  when: manual
  environment:
    name: development/S3/${CI_COMMIT_REF_NAME}
    action: stop

release beta S3:
  extends:
  - .rules:release:beta
  - .release
  - .release_S3
  environment:
    name: beta/S3

release RC S3:
  extends:
  - .rules:release:rc
  - .release
  - .release_S3
  environment:
    name: RC/S3

release stable S3:
  extends:
  - .rules:release:stable
  - .release
  - .release_S3
  environment:
    name: stable/S3
