validate:
  stage: validate
  extends:
  - .common:docker-in-docker
  - .rules:merge-requests
  before_script:
  - apk add -U make bash
  script: make build validate

prepare done:
  stage: validate
  extends:
  - .common:stage-done
